### ISSUE TITLE
Disable/remove all hms data ingest for wcoss2

### ISSUE THREAD

**Issue by ShelleyMelchior-NOAA** [NOAA-EMC/satingest#8]
Per discussion with NCO SPA TL, the downstream user of all hms data, HYSPLIT-SMOKE, is not being ported to WCOSS2. As a result, the hms data will not need to be ingested on WCOSS2.

Impacted files include:
`fix/aerosol`
`fix/aerosol.hms_smoke_final`
`fix/aerosol.hms_smoke_prelim`
`fix/aerosol.hms_smoke_prelim_early`

`fix/aerosol` has been modified in `release/satingest.v4.1.0` to modify var PROCESSING_FAMILIES to remove $PROC_FAM_group3, $PROC_FAM_group4, and $PROC_FAM_group8.
Comments were added to indicate that sections for enabling groups 3, 4, and 8 can be removed

All `fix/aerosol.hms_smoke_*` files may be removed.

**Comment by ShelleyMelchior-NOAA** [comment]
@ilianagenkova , @SudhirNadiga-NOAA , @SteveStegall-NOAA  

**for your general awareness**

Please see update in `release/satingest.v4.1.0`.
The change to `fix/aerosol` has been passed onto NCO SPA TL.

Once running in para on cactus without problem, the three specific `fix/aerosol.hms_smoke_*` files can be removed from the repository and `fix/aerosol` can be cleaned up further.

I took the lead on this b/c it was low hanging fruit and to shield you while folks are on leave and/or dealing w/ NESDIS fallout.

**Comment by ShelleyMelchior-NOAA** [comment]
Will need to remember to modify the wcoss2 transition Release Notes file:
https://docs.google.com/document/d/1kLpAJMp-xyVmQcmvJRPSeISzpXSB2I_ndcDjIIORXVE/edit?usp=sharing

**Comment by ilianagenkova** [comment]
It might be good to review all Release Notes, Readme, How to build notes
shortly before WCOSS2 goes live. Will put a reminder on my calendar.

**Comment by ilianagenkova** [comment]
See PR #16
